### ISSUE TITLE
cli shows wrong version number

### ISSUE THREAD

**Issue by PaulGoslawski** [andreasfelix/latticejson#34]
```sh
$latticejson --version
latticejson, version 0.0.2
```

isntalled 0.0.4

**Comment by felix-andreas** [comment]
This happens because you forget the `-U` when installing.

`pip install -Ue .`

Pip seems to cache some meta data like the version number if you use `-e` option without the `-U` option. Therefore it shows the old version number even though the newer version is installed.

The cache can be deleted by removing the`LatticeJSON.egg-info` directory.

For the same reason you got the error message in your terminal!
